import React from 'react'
import style from './service.module.css'
import Image from 'next/image'
import pro from "../../../public/profile.jpg"
import { title } from 'node:process'
import { url } from 'node:inspector'
export const metadata = {
  title:'Service page',
  description: "Generated by create next app",
  author:[{name:'Thapa Technical'},{name:'Thapa Technical'} , {url: "thapatechnical.com"}
  ],
  keywords:["next js ","react js","full stack"],
  icons:{icon:"/favicon.ico"}
}

const service = () => {
  return (
    <>
      <div className={style.common_heading}>service page</div>
      <div className='grid grid-cols-3 gap-4 px-4 py-4'>
        {/* 1 */}
        <div className="bg-white rounded-lg shadow-md p-3 hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-16 h-16 bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <Image src="/profile.jpg" width={500} height={500} className='w-full h-full rounded-full object-cover' alt='img' />
          </div>
          <h3 className="text-sm font-semibold text-center text-black mb-1">
            Thapa Technical
          </h3>
          <p className="text-xs text-black/80 text-center mb-1">
            Frontend Developer
          </p>
          <p className="text-[10px] text-black/70 text-center">
            React & TypeScript
          </p>
        </div>

        {/* 2 */}
        <div className="bg-white rounded-lg shadow-md hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-full h-full relative bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <Image
              src={pro}
              alt='profile'
              fill={true}
              quality={600} // quality of image
              priority={false} // lazy loading
              placeholder='blur'
              blurDataURL=''
            />
          </div>
        </div>

        {/* 3 */}
        <div className="bg-white rounded-lg shadow-md p-3 hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-16 h-16 bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <span className="text-xl font-bold text-purple-600">TT</span>
          </div>
          <h3 className="text-sm font-semibold text-center text-black mb-1">
            Thapa Technical
          </h3>
          <p className="text-xs text-black/80 text-center mb-1">
            Frontend Developer
          </p>
          <p className="text-[10px] text-black/70 text-center">
            React & TypeScript
          </p>
        </div>

        {/* 4 */}
        <div className="bg-white rounded-lg shadow-md p-3 hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-16 h-16 bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <span className="text-xl font-bold text-purple-600">TT</span>
          </div>
          <h3 className="text-sm font-semibold text-center text-black mb-1">
            Thapa Technical
          </h3>
          <p className="text-xs text-black/80 text-center mb-1">
            Frontend Developer
          </p>
          <p className="text-[10px] text-black/70 text-center">
            React & TypeScript
          </p>
        </div>

        {/* 5 */}
        <div className="bg-white rounded-lg shadow-md p-3 hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-16 h-16 bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <span className="text-xl font-bold text-purple-600">TT</span>
          </div>
          <h3 className="text-sm font-semibold text-center text-black mb-1">
            Thapa Technical
          </h3>
          <p className="text-xs text-black/80 text-center mb-1">
            Frontend Developer
          </p>
          <p className="text-[10px] text-black/70 text-center">
            React & TypeScript
          </p>
        </div>

        {/* 6 */}
        <div className="bg-white rounded-lg shadow-md p-3 hover:shadow-lg hover:-translate-y-2 transition-all duration-300">
          <div className="w-16 h-16 bg-blue-200 rounded-full mx-auto mb-3 flex items-center justify-center">
            <span className="text-xl font-bold text-purple-600">TT</span>
          </div>
          <h3 className="text-sm font-semibold text-center text-black mb-1">
            Thapa Technical
          </h3>
          <p className="text-xs text-black/80 text-center mb-1">
            Frontend Developer
          </p>
          <p className="text-[10px] text-black/70 text-center">
            React & TypeScript
          </p>
        </div>
      </div>
    </>
  )
}

export default service

