import './globals.css';
// import Navigation from "../../component/Navigation"; // Moved to route-specific layouts
import type { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
